### PR TITLE
Added SCORM interactions support.

### PR DESCRIPTION
**Pull request by chris-steele**
https://adaptlearning.atlassian.net/browse/ABU-690

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
example.json and README need updating with the new `_recordInteraction` property... either that or we don't bother having one on each question component? there is a 'disableInteractionTracking' in spoor, it's just commented out at the moment

**Comment by moloko** [comment]
the value of cmi.interactions.n.student_response is incorrect, it's currently using the option text but this is both wrong and can cause problems if the option text is very long.
According to the SCORM documentation, the correct format for a 'choice' type response is:
"one or more characters separated by a comma. Integers (0-9), letters (a - z) or both may be used. Each possible response is limited to a single character. If there are more than 26 possibilities, then a performance type response must be used"
Typically this would equate to the format "1,3" (if the user chose options 1 and 3)

**Comment by chris-steele** [comment]
Yeah not a great decision of mine, but I remember I used the text as there wasn't an identifier (not like in the good old Papaya days). I could use the index of the selected items rather than impose a requirement to specify identifiers in the JSON, if that sounds reasonable?

**Comment by moloko** [comment]
sounds great, just need to make sure the index is 1-based and copes OK if `_isRandom` is set to `true`

**Comment by chris-steele** [comment]
Will leave in _recordInteraction property as first project using cmi.interactions needed this level of control(!) Have changed logic so that disableInteractionTracking is the overriding setting. See framework and spoor PRs

**Comment by moloko** [comment]
as discussed, could you amend this so that it uses the '_index' property that exists already rather than adding a new `_originalIndex` property? Just copy what I've done in #112

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
