### PR TITLE
ABU-676: Correctly save/restore _userAnswer

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by moloko** [comment]
+1 though use of 'indexes' instead of 'indices' sounds wrong to me, however the former use is more common in programming so I'll just have to suck it up :-)

**Comment by taylortom** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by zenduo** [comment]
+1

**Pull request merged**
