### PR TITLE
Refactor randomisation code out into a separate method

### PR DESCRIPTION
**Pull request by moloko**
so as to make implementing randomisation in GMCQ nice and DRY.

Remove comments that were just repeating what was obvious from the code, add/amends comment where clarity needed.

Amend getResponse() so that the 1-based index(es) of the option(s) the user chose is/are returned instead of the option text, in line with the SCORM spec for 'choice' type interactions.

Bump version to 2.0.1

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by taylortom** [comment]
Is this intended for master?

**Comment by moloko** [comment]
@taylortom yes indeedy

**Pull request merged**
