### PR TITLE
Add _shouldDisplayAttempts

### PR DESCRIPTION
**Pull request by chucklorenz**
"_shouldDisplayAttempts" required by all questions. JSON copied from contrib-textInput.

### CODE REVIEW

**Comment by zenduo** [comment]
+1

**Comment by dancgray** [comment]
+1 it's missing from the example.json as well. Could you add that in this PR please.

**Comment by hrajotia** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
