### PR TITLE
Accessibility merge

### PR DESCRIPTION
**Pull request by oliverfoster**

### CODE REVIEW

**Comment by oliverfoster** [comment]
Removed radio button as radio and checkbox have different input keys in some browsers. 

Javascript already enforces the radio style behaviour where needed, regardless of element. CSS styles up the element icon as necessary.

This change just makes the input keys uniform.

**Comment by moloko** [comment]
+1

**Comment by taylortom** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
