### PR TITLE
issue/3279 Fix for active item on reset

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adaptlearning/adapt_framework/issues/3279

### Fixed
* Active item must match model when reset

### CODE REVIEW

**Review by deltanetdan — APPROVED** [review]
Fixes the issue for Lars, but still needs _isCorrectAnswerShown: false adding [here](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L329) to fix the original issue.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by joe-allen-89** [comment]
Just tested this on iOS and it seems to cause an issue by not allowing you to select any options. Tested on an older version of iOS (13.1.2), currently updating to the latest and will retest on that.

**Comment by joe-allen-89** [comment]
After a long wait for an update, this issue is still seen in the latest version of iOS.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — COMMENTED** [review]
That seems to have done the trick. Working on iOS, and on reset allowing you to select the same option.

**Review by deltanetdan — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]
Tested with iOS and latest framework.

**Pull request merged**
