### PR TITLE
refactor randomisation code out into separate function

### PR DESCRIPTION
**Pull request by moloko**
so as to make adding randomisation to GMCQ (see [GCMQ issue 83](https://github.com/adaptlearning/adapt-contrib-gmcq/issues/83))  nice and DRY

also remove comments that were simply restating what was obviously happening in the code, re-write/add comments where helpful

### CODE REVIEW

**Comment by hrajotia** [comment]
+1

**Comment by belal-almassri-spongeuk** [comment]
+1

**Comment by zenduo** [comment]
+1

**Comment by zenduo** [comment]
+1 should this be done as a release? As this is broken for anyone downloading the current framework.

**Comment by moloko** [comment]
I will do the PR to master and release tomorrow. I can't do it from this as I forked from develop which has other changes that shouldn't go into master.

**Comment by moloko** [comment]
@zenduo master PR in #112 
sorry about delay

**Pull request merged**
